apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-135107-0mhg-service
spec:
  selector:
    app: enterprise-system-135107-0mhg
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
